CPP-642 migrate from circleci/* to cimg/*
Financial-Times/github-apps-config-next pull request #38
Opened 2021-11-22 13:32 UTC by serena97

These images will be EOL from Dec 31st, and we should migrate to the modern cimg/* equivalents.

2021-11-30 18:31 UTC, serena97 commented
will squash commits after someone reviews - thought I would leave it there so people can see the different ways I've tried to resolve the issue

2021-12-02 10:52 UTC, ivomurrell requested changes
Looks like [manage-github-apps](https://github.com/Financial-Times/manage-github-apps) never got a nori PR to fix its preinstall script. If we merge https://github.com/Financial-Times/manage-github-apps/pull/109, the CircleCI script should pass without us having to ignore the script

2021-12-02 14:42 UTC, serena97 commented
The error [where circleci will exit with code 123 ](https://app.circleci.com/pipelines/github/Financial-Times/github-apps-config-next/81/workflows/8be3ff66-ddee-41d1-8fca-f32abc767130/jobs/95) is caused by npx running with preinstall. If there is something in preinstall, even if it is just a echo and without the check engine script, it will still error ([see build with dummy2](https://app.circleci.com/pipelines/github/Financial-Times/github-apps-config-next/81/workflows/8be3ff66-ddee-41d1-8fca-f32abc767130/jobs/95) where dummy2 branch includes a [preinstall script with just an echo](https://github.com/Financial-Times/manage-github-apps/compare/main...dummy2)) Also the "*.json" is needed or else [this error](https://app.circleci.com/pipelines/github/Financial-Times/github-apps-config-next/82/workflows/a55d1626-6fb9-45cb-ab69-4377eb832344/jobs/96) happens.

It was really hard to debug because I'm not able to replicate it locally with running cimg/node:12.22 in docker, and also running npx with verbose doesn't show the preinstall logs

2021-12-02 18:26 UTC, ivomurrell commented
Is it not erroring because you need to confirm installation of new packages before running them with `npx` since npm 7?

> If any requested packages are not present in the local project dependencies, then they are installed to a folder in the npm cache, which is added to the PATH environment variable in the executed process. A prompt is printed (which can be suppressed by providing either --yes or --no).

from https://docs.npmjs.com/cli/v7/commands/npx#description

Can you just pass a `--yes` flag to `npx` rather than manually installing the dependency beforehand?

2021-12-02 18:49 UTC, serena97 commented
I tried [passing --yes ](https://app.circleci.com/pipelines/github/Financial-Times/github-apps-config-next/85/workflows/fb9e0423-7e9b-4464-bc23-997dff3a391c/jobs/100) and it doesn't fix the build, which doesn't come as a surprise to me because it was still installing manage-github-apps in [previous builds with npx without specifying yes](https://app.circleci.com/pipelines/github/Financial-Times/github-apps-config-next/80/workflows/0d4649d7-776c-47ff-ba00-a8936b28b563/jobs/91). I am going to revert back to my original solution

2021-12-07 19:49 UTC, serena97 commented
npx errors out with 1 is highlighted in this open issue, https://github.com/npm/cli/issues/4003. 
if I try `find manage-github-apps/ -type f -name "*.json" | xargs -n 1 npx --verbose github:Financial-Times/manage-github-apps#0d261812de10488a028cf783d7c2980f6d5e54d7 validate-config --config`  where the commit sha [corresponds to this change](https://github.com/Financial-Times/manage-github-apps/commit/0d261812de10488a028cf783d7c2980f6d5e54d7), it works

2021-12-08 10:57 UTC, ivomurrell approved these changes

2021-12-08 14:20 UTC, merged